using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace TinyERP4Fun
{
    public static class Localization
    {
        public static void SetEN()
        {
            currentLocalizatin = englishLocalizatin;
        }
        public static void SetRU()
        {
            currentLocalizatin = russianLocalizatin;
        }
        public static void SetLoaded()
        {
            throw new NotImplementedException();
        }
        public static Dictionary<string, string> currentLocalizatin { get; set; }
        public static Dictionary<string, string> LoadedLocalizatin { get; set; }

        private static readonly Dictionary<string, string> englishLocalizatin = new Dictionary<string, string>
        {
            ["City"] = "City",
            ["Cities"] = "Cities",
            ["State"] = "State",
            ["States"] = "States",
            ["Country"] = "Country",
            ["Countries"] = "Countries",
            ["Currency"] = "Currency",
            ["Base Currency"] = "Base Currency",
            ["Currencies"] = "Currencies",
            ["Business Direction"] = "Business Direction",
            ["Business Directions"] = "Business Directions",
            ["Cost Item"] = "Cost Item",
            ["Cost Items"] = "Cost Items",
            ["Head Company"] = "Head Company",
            ["TIN"] = "TIN",
            ["TIN2"] = "TIN2",
            ["Company"] = "Company",
            ["Companies"] = "Companies",
            ["Department"] = "Department",
            ["Departments"] = "Departments",
            ["Position"] = "Position",
            ["Positions"] = "Positions",
            ["Person"] = "Person",
            ["Persons"] = "People",
            ["People"] = "People",
            ["Employee"] = "Employee",
            ["Employees"] = "Employees",
            ["User"] = "User",
            ["Users"] = "Users",
            ["Document Type"] = "Document Type",
            ["Document Types"] = "Document Types",
            ["Expence"] = "Expence",
            ["Expences"] = "Expences",
            ["Find"] = "Find",
            ["Search"] = "Search",
            ["Back to Full List"] = "Back to Full List",
            ["Back to List"] = "Back to List",
            ["Create New"] = "Create New",
            ["Create"] = "Create",
            ["Edit"] = "Edit",
            ["Details"] = "Details",
            ["Delete"] = "Delete",
            ["Save"] = "Save",
            ["Name"] = "Name",
            ["Name2"] = "Name",
            ["First Name"] = "First Name",
            ["Last Name"] = "Last Name",
            ["Full Name"] = "Full Name",
            ["Are you sure you want to delete this?"] = "Are you sure you want to delete this?",
            ["Previous"] = "Previous",
            ["Next"] = "Next",
            ["Common"] = "Common",
            ["Home"] = "Home",
            ["Privacy"] = "Privacy",
            ["Login"] = "Login",
            ["Logout"] = "Logout",
            ["Register"] = "Register",
            ["Our Company"] = "Our Company",
            ["Address"] = "Address",
            ["Code"] = "Code",
            ["Part001Name"] = "Name of 1/100 part",
            ["Part001Name2"] = "Name of 1/100 part",
            ["Active"] = "Active",
            ["Base"] = "Base",
            ["Birthday"] = "Birthday",
            ["Is Employee"] = "Is Employe",
            ["Is Chief"] = "Is Chief",
            ["Number"] = "Number",
            ["Role"] = "Role",
            ["Head Company"] = "Head Company",
            ["Base Currency"] = "Base Currency",
            ["Currency Rates"] = "Currency Rates",
            ["Currency Rate"] = "Currency Rate",
            ["Update BYN from Course Provider"] = "Update BYN from Course Provider",
            ["Currecy Scale"] = "Currecy Scale",
            ["Date Rate"] = "Date Rate",
            ["Document Number"] = "Document Number",
            ["Document Date"] = "Document Date",
            ["Amount Of Payment"] = "Amount Of Payment",
            ["Purpose Of Payment"] = "Purpose Of Payment",
            ["Desired Payment Date"] = "Desired Payment Date",
            ["Transfer Of Payment"] = "Transfer Of Payment",
            ["Payment Date"] = "Payment Date",
            ["Approved"] = "Approved",
            ["Declined"] = "Declined",
            ["Approved Payment Date"] = "Approved Payment Date",
            ["From"] = "From",
            ["To"] = "To",
            ["Not Processed"] = "Not Processed",
            ["Filter"] = "Filter",
            ["Amount of Expenses"] = "Amount of Expenses",
            ["Administration"] = "Administration",
            ["Warehouses"] = "Warehouses",
            ["Warehouse"] = "Warehouse",
            ["Stock"] = "Stock",
            ["Units"] = "Units",
            ["Unit"] = "Unit",
            ["Items"] = "Items",
            ["Item"] = "Item",
            ["Operation Date"] = "Operation Date",
            ["Quantity"] = "Quantity",
            ["Movements"] = "Movements",

        };
        private static readonly Dictionary<string, string> russianLocalizatin = new Dictionary<string, string>
        {
            ["City"] = "Город",
            ["Cities"] = "Города",
            ["State"] = "Область/Штат",
            ["States"] = "Области/Штаты",
            ["Country"] = "Страна",
            ["Countries"] = "Страны",
            ["Currency"] = "Валюта",
            ["Base Currency"] = "Базовая Валюта",
            ["Currencies"] = "Валюты",
            ["Business Direction"] = "Направление Бизнеса",
            ["Business Directions"] = "Направления Бизнеса",
            ["Cost Item"] = "Статья Затрат",
            ["Cost Items"] = "Статьи Затрат",
            ["Head Company"] = "Головная Организация",
            ["TIN"] = "ИНН",
            ["TIN2"] = "КПП",
            ["Company"] = "Организация",
            ["Companies"] = "Организации",
            ["Department"] = "Отдел",
            ["Departments"] = "Отделы",
            ["Position"] = "Должность",
            ["Positions"] = "Должности",
            ["Person"] = "Персона",
            ["Persons"] = "Персоны",
            ["People"] = "Персоны",
            ["Employee"] = "Сотрудник",
            ["Employees"] = "Сотрудники",
            ["User"] = "Пользователь",
            ["Users"] = "Пользователи",
            ["Document Type"] = "Тип документа",
            ["Document Types"] = "Типы документов",
            ["Expence"] = "Платеж",
            ["Expences"] = "Перечень платежей",
            ["Find"] = "Найти",
            ["Search"] = "Поиск",
            ["Back to Full List"] = "Назад к полному списку",
            ["Back to List"] = "Назад к списку",
            ["Create New"] = "Создать",
            ["Create"] = "Создать",
            ["Edit"] = "Редактировать",
            ["Details"] = "Подробнее",
            ["Delete"] = "Удалить",
            ["Save"] = "Сохранить",
            ["Name"] = "Наименование",
            ["Name2"] = "Наименование в родительном падеже",
            ["First Name"] = "Имя",
            ["Last Name"] = "Фамилия",
            ["Full Name"] = "Имя и Фамилия",
            ["Are you sure you want to delete this?"] = "Вы действительно хотите удалить?",
            ["Previous"] = "Назад",
            ["Next"] = "Вперед",
            ["Common"] = "Общее",
            ["Home"] = "Домой",
            ["Privacy"] = "Политика конфиденциальности",
            ["Login"] = "Вход",
            ["Logout"] = "Выход",
            ["Register"] = "Регистрация",
            ["Our Company"] = "Наша Организация",
            ["Address"] = "Адрес",
            ["Code"] = "Код",
            ["Part001Name"] = "Наименование 1/100 части",
            ["Part001Name2"] = "Наименование 1/100 части в родительном падеже",
            ["Active"] = "Активная",
            ["Base"] = "Базовая",
            ["Birthday"] = "Дата рождения",
            ["Is Employee"] = "Сотрудник",
            ["Is Chief"] = "Руководитель",
            ["Number"] = "Номер",
            ["Role"] = "Роль",
            ["Head Company"] = "Головная организация",
            ["Base Currency"] = "Базовая валюта",
            ["Currency Rates"] = "Курсы валют",
            ["Currency Rate"] = "Курс валюты",
            ["Update BYN from Course Provider"] = "Обновить BYN от поставщика курсов",
            ["Currecy Scale"] = "Шкала курса",
            ["Date Rate"] = "Дата курса",
            ["Document Number"] = "Номер документа",
            ["Document Date"] = "Дата документа",
            ["Amount Of Payment"] = "Сумма платежа",
            ["Purpose Of Payment"] = "Назначение платежа",
            ["Desired Payment Date"] = "Желаемая дата оплаты",
            ["Transfer Of Payment"] = "Перенос платежа",
            ["Payment Date"] = "Дата оплаты",
            ["Approved"] = "Одобрен",
            ["Declined"] = "Отклонен",
            ["Approved Payment Date"] = "Утвержденная дата оплаты",
            ["From"] = "С",
            ["To"] = "По",
            ["Not Processed"] = "Не обработан",
            ["Filter"] = "Фильтр",
            ["Amount of Expenses"] = "Сумма затрат",
            ["Administration"] = "Администрирование",
            ["Warehouses"] = "Склады",
            ["Warehouse"] = "Склад",
            ["Stock"] = "Складские запасы",
            ["Units"] = "Единицы измерения",
            ["Unit"] = "Единица измерения",
            ["Items"] = "Материальные ценности",
            ["Item"] = "Материальная ценность",
            ["Operation Date"] = "Дата операции",
            ["Quantity"] = "Количество",
            ["Movements"] = "Перемещения",
            
        };
    }
}
